### ISSUE TITLE
HealthCheckRegistry bean auto-configuration

### ISSUE THREAD

**Issue by astefanutti** [astefanutti/metrics-cdi#13]
Metrics CDI doesn't automatically add a `HealthCheckRegistry` bean and register the `HealthCheck` beans for the time being. That would be quite easy to add support for that, as it's quite similar to what's being done for the `MetricRegistry` and `Metric` beans.

**Comment by bvarner** [comment]
:+1 for this enhancement.

I was just looking into adding HealthChecks to a microservice app running in thorntail 2.0.0, using metrics-cdi.

I could do the lifting on this one, if you're up for a contribution and quick release cycle.

**Comment by astefanutti** [comment]
> I could do the lifting on this one, if you're up for a contribution and quick release cycle.

It would be great! I can cut a release right after your PR gets merged.

**Comment by astefanutti** [comment]
Closed with #22. Thanks @bvarner for the great contribution!
