### ISSUE TITLE
MetricsExtension tries to register Metric from generic producer method

### ISSUE THREAD

**Issue by sadimusi** [astefanutti/metrics-cdi#18]
I defined a producer method for `Timer` instances, based on a qualifier. It looks something like this:
```java
    @Produces
    @SomeFancyQualifier("any")
    Timer getFancyTimer(InjectionPoint injectionPoint) {
        return getFanyTimer(getQualifier(injectionPoint, SomeFancyQualifier.class).value());
    }
```
Unfortunately, `MetricsExtension` thinks I want to register a Timer here and calls my producer method with no injectionPoint. You probably can't reliably catch that case, but it would already help if I could return `null` to indicate that no `Timer` should be registered. Right now that causes a `NullPointerException` and I therefore have to return some dummy `Timer` which clutters my statistics.

**Comment by astefanutti** [comment]
Ah that's an interesting use case. I think it is possible to actually check whether:
* There is an parameter of type `InjectionPoint` in the producer method signature
* Or there is another qualifier than `@Default`

And skip the registration of the custom metric.

For the later, I think it makes as well since the alternative metrics producer methods from the extension produce metric beans with the `@Default` qualifier so that would be more consistent.

Let me know what you think. I'll work on it ASAP, though if you could contribute a PR that'd be event better 😉!

**Comment by sadimusi** [comment]
In my opinion the second option makes more sense. Registering only producers for `@Default` timers is consistent and easily understood. With the first option I can think of genuine use cases where the problem would still arise:

```java
    @Produces
    @UserGroupActionMeter
    Meter getUserGroupActionMeter(Session session) {
        return getUserGroupActionMeter(session.getUserGroup());
    }
```

While I'm generally all for contributing to great open-source projects, it looks like I don't have enough budget to do it this time 😕

**Comment by astefanutti** [comment]
I think both options are not mutually exclusive so both safe guard address more cases. 

No problem. It's not that much a change so I should be able to do it soon.

**Comment by sadimusi** [comment]
Yeah you're right, and I can't think of a case where a producer with an `InjectionPoint` parameter should be registered in the `MetricsRegistry`. I'm looking forward to your fix 😊

**Comment by astefanutti** [comment]
Should be fixed with bda4712718bfbb9c8ba14992ecdcc2eb53dd3031. I'll cut a new release once CI has passed.

**Comment by astefanutti** [comment]
Version `1.4.0` that contains this fix has been released.

**Comment by sadimusi** [comment]
Thanks for the speedy fix and release, it works great now 👍

**Comment by astefanutti** [comment]
Great thanks for the feedback!
