### ISSUE TITLE
metrics are not written to dropwizard environment.metrics()

### ISSUE THREAD

**Issue by tobilarscheid** [astefanutti/metrics-cdi#19]
In dropwizard, there is a default metrics registry that collects all the standard metrics collected by dropwizard. This registry is available in the `run` method of the `application class`: http://www.dropwizard.io/1.1.0/docs/getting-started.html#gs-application
Unfortunately, it is not linked to the default metric registry that `metrics-cdi` creates.
At the moment, I am a little clueless how to bring these to worlds together...

**Comment by astefanutti** [comment]
One potential solution is to expose the default metrics registry used by Dropwizard as a CDI bean, e.g.:

    @Produces
    MetricRegistry dropwizardRegistry() {
         // return the default Dropwizard metrics registry
    }

You may have to have the correct dependencies to have CDI working with Dropwizard, see: https://stackoverflow.com/a/26756789/601347.

**Comment by tobilarscheid** [comment]
yes, I have CDI working with dropwizard. However, in the application class there is no CDI context available - so I fail to see how to fuel that producer you proposed.

**Comment by astefanutti** [comment]
Couldn't the producer be declared in a CDI bean within your application ?

**Comment by tobilarscheid** [comment]
hm, yes, solution is the following code in the application class:

```
private static MetricRegistry registry;

    @Produces
    public static MetricRegistry getRegistry() {
        return registry;
    }
```

and then, in the run method: `registry = environment.metrics();`

not beautiful, but it works. Thanks for your input!
