### ISSUE TITLE
Schedule & Timeout annotated method cannot be decorated

### ISSUE THREAD

**Issue by McFoggy** [astefanutti/metrics-cdi#2]
Integrating the library I came across having some methods not publishing metrics as expected.

Those methods are some EJB methods which are _timer_ based.

Thus the followings example do not work

__1. Example with @Timeout__
```java
@Timed(name = "schedule")
@Timeout
public void scheduledMethod() {
}
```
__2. Example with @Schedule__
```java
@Schedule(hour = "*", minute = "*", second = "*", persistent = false)
@Timed(name = "schedule")
public void scheduledMethod() {
}
```

I'll provide test cases in a fork branch.

Not sure it is normal or if it comes from a miss usage. Feel free to comment if I am doing soemthing wrong.

**Comment by astefanutti** [comment]
Hi Matthieu,

Thanks a lot for reporting. Indeed, instrumentation of `@Schedule` and `@Timeout` methods isn't currently supported. It should be straightforward though to add that support by adding a `@AroundTimeout` interceptor method along with the existing `@AroundConstruct` and `@AroundInvoke` ones in https://github.com/astefanutti/metrics-cdi/blob/964e26a321b777613d07f33812bc32f57a5eb13e/impl/src/main/java/io/astefanutti/metrics/cdi/TimedInterceptor.java#L46-L54 and the other interceptors.

I'll work on it ASAP though feel free to contribute if you will in the meantime :-)

**Comment by McFoggy** [comment]
I will provide it. I didn't thought it was as easy as that. I am not totally new to CDI but I was not aware that timeouts methods had their own interceptor scheme.

**Comment by astefanutti** [comment]
Thanks. I'll do a release ASAP.

**Comment by McFoggy** [comment]
Ok thank you, that will save me to have to maintain my own release in my company.

**Comment by astefanutti** [comment]
I've just release version `1.1.0` to Maven Central: http://repo1.maven.org/maven2/io/astefanutti/metrics/cdi/metrics-cdi/1.1.0/

Thanks for your contribution!

**Comment by McFoggy** [comment]
You're welcome and thanks for the fast release.
